# Generated by Django 5.1.3 on 2024-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_activate',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
